version: '3.3'

services:

  init_alice:
    image: wjyask/tscs-node:latest
    entrypoint: ["/usr/local/bin/scs"]
    command: ["key", "generate-node-key", "--base-path", "/data", "--chain", "dev"]
    volumes:
      - ./db/alice:/data
  
  init_bob:
    image: wjyask/tscs-node:latest
    entrypoint: ["/usr/local/bin/scs"]
    command: ["key", "generate-node-key", "--base-path", "/data", "--chain", "dev"]
    volumes:
      - ./db/bob:/data

  alice:
    image: wjyask/tscs-node:latest
    entrypoint: ["/usr/local/bin/scs", "--database", "auto", "--chain", "dev"]
    command: ["--pruning", "archive", "--base-path", "/data", "--alice", "--rpc-max-connections", "100", "--rpc-cors", "all", "--rpc-methods", "Unsafe", "--unsafe-rpc-external"]
    volumes:
      - ./db/alice:/data 
    ports:
      - 30333:30333
      - 9944:9944 
      - 9933:9933
    depends_on:
      - init_alice

    networks:
      - dscs
      
  bob:
    image: wjyask/tscs-node:latest
    entrypoint: ["/usr/local/bin/scs", "--database", "auto", "--chain", "dev"]
    command: ["--pruning", "archive", "--base-path", "/data", "--bob", "--rpc-max-connections", "100", "--rpc-cors", "all", "--rpc-methods", "Unsafe", "--unsafe-rpc-external"]
    volumes:
      - ./db/bob:/data 
    ports:
      - 30334:30333
      - 8545:9944 # 
      - 9934:9933

    depends_on:
      - init_bob
    networks:
      - dscs


networks:
  dscs:
    driver: bridge
    
    