version: '1.0'

services:

  init_full_node:
    image: wjyask/tscs-node:1.0
    entrypoint: ["bash", "-c", "/usr/local/bin/normal_node_init.sh"]
    volumes:
      - ./full_node:/data 


  full_node:
    image: wjyask/tscs-node:1.0
    command: ["--pruning", "archive", "--rpc-max-connections", "100", "--rpc-cors=all"]
    volumes:
      - ./full_node:/data 
    ports:
      - 30333:30333
      - 8545:9944 # 兼容以太坊 
      - 9933:9933
    

  init_validator_node1:
    image: wjyask/tscs-node:1.0
    entrypoint: ["bash", "-c", "/usr/local/bin/validator_node_init.sh"]
    environment:
      - SESSION_KEYS_PASSWORD=root
      - SESSION_KEYS_INDEX=1

  validator_node1:
    image: wjyask/tscs-node:1.0
    command: ["--validator", "--pruning", "archive", "--reserved-nodes", "/ip4/127.0.0.1/tcp/30333/p2p/12D3KooWDLfW4jqc39rpBM2dS4UDp9TEqu2MbLrffEDp2bTQt61Q"]
    environment:
      - SESSION_KEYS_PASSWORD=root
      - SESSION_KEYS_INDEX=1
    ports:
      - 30334:30333
      - 9945:9944
      - 9934:9933
    
    volumes:
      - ./node1:/data
    
    deploy:
      resources:
        limits:
          cpus: '12'
          memory: '18G'
        reservations:
          cpus: '6'
          memory: '12G'


  init_validator_node2:
    image: wjyask/tscs-node:1.0
    entrypoint: ["bash", "-c", "/usr/local/bin/validator_node_init.sh"]
    environment:
      - SESSION_KEYS_PASSWORD=root
      - SESSION_KEYS_INDEX=2
    volumes:
      - ./node2:/data


  validator_node2:
    image: wjyask/tscs-node:1.0
    environment:
      - SESSION_KEYS_PASSWORD=root
      - SESSION_KEYS_INDEX=2
    ports:
      - 30335:30334
      - 9946:9944
      - 9935:9934

    volumes:
    - ./node2:/data
    command: ["--validator", "--pruning", "archive", "--reserved-nodes", "/ip4/127.0.0.1/tcp/30333/p2p/12D3KooWDLfW4jqc39rpBM2dS4UDp9TEqu2MbLrffEDp2bTQt61Q"]

    deploy:
      resources:
        limits:
          cpus: '12'
          memory: '18G'
        reservations:
          cpus: '6'
          memory: '12G'

    depends_on:
      - node1 


# networks:
#   tscs:
#     driver: bridge
    
    
