version: '1.0.0'

services:

  init_full_node:
    image: wjyask/tscs-node
    entrypoint: ["bash", "-c", "/usr/local/bin/normal_node_init.sh"]
    volumes:
      - ./full_node:/data 

  full_node:
    image: wjyask/tscs-node
    entrypoint: ["/usr/local/bin/scs", "--database", "auto", "--base-path", "/data"]
    command: ["--pruning", "archive", "--rpc-max-connections", "100", "--rpc-cors", "all", "--rpc-methods", "Unsafe", "--unsafe-rpc-external"]
    volumes:
      - ./full_node:/data 
    ports:
      - 30333:30333
      - 8545:9944
      - 9933:9933
    networks:
      - tscs
    

  init_validator_node:
    image: wjyask/tscs-node
    entrypoint: ["bash", "-c", "/usr/local/bin/validator_node_init.sh"]
    environment:
      - SESSION_KEYS_PASSWORD=root
    volumes:
      - ./validator_node:/data

  validator_node:
    image: wjyask/tscs-node
    entrypoint: ["/usr/local/bin/scs", "--database", "auto", "--base-path", "/data"]
    command: ["--validator", "--pruning", "archive"]
    environment:
      - SESSION_KEYS_PASSWORD=root
    ports:
      - 30334:30333
      - 9944:9944
      - 9934:9933
    
    volumes:
      - ./validator_node:/data
    
    networks:
      - tscs
    deploy:
      resources:
        limits:
          cpus: '12'
          memory: '18G'
        reservations:
          cpus: '6'
          memory: '12G'


networks:
  tscs:
    driver: bridge
    
    
