version: '1.0'

services:

  init_rpc_node:
    image: tscs-node:latest
    entrypoint: ["bash", "-c", "/usr/local/bin/validator_node_init.sh"]
    volumes:
      - ./rpc_node1:/data 
  

  rpc_node:
    image: tscs-node:latest
    command: ["--pruning", "archive", “--rpc-max-connections", "100"]
    volumes:
      - ./rpc_node1:/data 

  init_node1:
    image: tscs-node:latest
    entrypoint: ["bash", "-c", "/usr/local/bin/validator_node_init.sh"]
    environment:
      - SESSION_KEYS_PASSWORD=wjy
      - SESSION_KEYS_INDEX=1
    volumes:
      - ./node1:/data

  node1:
    image: tscs-node:latest
    command: ["--pruning", "archive","--validator", "--reserved-nodes", "/dns/node1/tcp/30333/p2p/12D3KooWA2rwQvFZ7RWo53Aggm4RA7rP2VNqzvtjBqvNaDqwUrZz"]
    environment:
      - SESSION_KEYS_PASSWORD=wjy
      - SESSION_KEYS_INDEX=1
    ports:
      - 30333:30333
      - 9944:9944
      - 9934:9933
    
    volumes:
      - ./node1:/data
    
    deploy:
      resources:
        limits:
          cpus: '12'
          memory: '18G'
        reservations:
          cpus: '6'
          memory: '12G'


  init_node3:
    image: tscs-node:latest
    entrypoint: ["bash", "-c", "/usr/local/bin/validator_node_init.sh"]
    environment:
      - SESSION_KEYS_PASSWORD=wjy
      - SESSION_KEYS_INDEX=3
    volumes:
      - ./node3:/data


  node3:
    image: tscs-node:latest
    environment:
      - SESSION_KEYS_PASSWORD=wjy
      - SESSION_KEYS_INDEX=3
    ports:
      - 30333:30333
      - 9944:9944
      - 9933:9933

    volumes:
    - ./node3:/data

    command: ["--pruning", "archive","--validator", "--reserved-nodes", "/dns/node1/tcp/30333/p2p/12D3KooWA2rwQvFZ7RWo53Aggm4RA7rP2VNqzvtjBqvNaDqwUrZz"]

    deploy:
      resources:
        limits:
          cpus: '12'
          memory: '18G'
        reservations:
          cpus: '6'
          memory: '12G'

    depends_on:
      - node1 
    
    
