version: '3.2'

services:

  init_full_node:
    image: wjyask/tscs-node
    entrypoint: ["bash", "-c", "/usr/local/bin/normal_node_init.sh"]
    volumes:
      - ./full_node:/data 

  full_node:
    image: wjyask/tscs-node
    command: ["--pruning", "archive",  "--database", "auto", "--rpc-max-connections", "100", "--rpc-cors", "all", "--rpc-methods", "Unsafe", "--unsafe-rpc-external"]
    volumes:
      - ./full_node:/data 
    ports:
      - 30333:30333
      - 8545:9944
      - 9933:9933
    depends_on:
      - init_full_node
    networks:
      - tscs
    
  init_validator_node:
    image: wjyask/tscs-node
    entrypoint: ["bash", "-c", "/usr/local/bin/validator_node_init.sh"]
    environment:
      - SESSION_KEYS_PASSWORD=root
      - INDEX = 1
    volumes:
      - ./validator_node:/data

  validator_node:
    image: wjyask/tscs-node
    command: ["--validator", "--pruning", "archive", "--database", "auto"]
    ports:
      - 30334:30333
      - 9944:9944
      - 9934:9933
    depends_on:
      - init_validator_node
    volumes:
      - ./validator_node:/data
    
    networks:
      - tscs
  
  export_blocks:
  image: wjyask/tscs-node
  entrypoint: ["/usr/local/bin/scs"]
  command: ["export-blocks", "--chain", "staging", "--database", "auto", "--base-path", "/data", "--pruning", "archive", "--to", "1472954", "/data/1472954.json"]
  volumes:
    - ./db:/data 
  networks:
      - tscs
      
  import_blocks:
    image: wjyask/tscs-node
    entrypoint: ["/usr/local/bin/scs"]
    command: ["import-blocks", "--chain", "staging", "--database", "auto", "--base-path", "/data/new", "--pruning", "archive", "/data/1472954.json"]
    volumes:
      - ./db:/data 
    networks:
      - tscs

networks:
  tscs:
    driver: bridge
    
    
