version: '1.0'

services:

  init_rpc_node:
    image: tscs-node:latest
    entrypoint: ["bash", "-c", "/usr/local/bin/validator_node_init.sh"]
    volumes:
      - ./rpc_node:/data 


  rpc_node:
    image: tscs-node:latest
    command: ["--pruning", "archive", "--rpc-max-connections", "100"]
    volumes:
      - ./rpc_node:/data 
    ports:
      - 30333:30333
      - 9944:9944
      - 9933:9933
    networks:
      - tscs
    

  init_node1:
    image: tscs-node:latest
    entrypoint: ["bash", "-c", "/usr/local/bin/validator_node_init.sh"]
    environment:
      - SESSION_KEYS_PASSWORD=wjy
      - SESSION_KEYS_INDEX=1
    volumes:
      - ./node1:/data

  node1:
    image: tscs-node:latest
    command: ["--pruning", "archive", "--reserved-nodes", "/ip4/127.0.0.1/tcp/30333/p2p/12D3KooWDLfW4jqc39rpBM2dS4UDp9TEqu2MbLrffEDp2bTQt61Q"]
    environment:
      - SESSION_KEYS_PASSWORD=wjy
      - SESSION_KEYS_INDEX=1
    ports:
      - 30334:30333
      - 9945:9944
      - 9934:9933
    
    volumes:
      - ./node1:/data
    networks:
      - tscs
    
    deploy:
      resources:
        limits:
          cpus: '12'
          memory: '18G'
        reservations:
          cpus: '6'
          memory: '12G'


  init_node3:
    image: tscs-node:latest
    entrypoint: ["bash", "-c", "/usr/local/bin/validator_node_init.sh"]
    environment:
      - SESSION_KEYS_PASSWORD=wjy
      - SESSION_KEYS_INDEX=3
    volumes:
      - ./node3:/data


  node3:
    image: tscs-node:latest
    environment:
      - SESSION_KEYS_PASSWORD=wjy
      - SESSION_KEYS_INDEX=3
    ports:
      - 30335:30334
      - 9946:9944
      - 9935:9934

    volumes:
    - ./node3:/data
    command: ["--pruning", "archive", "--reserved-nodes", "/ip4/127.0.0.1/tcp/30333/p2p/12D3KooWDLfW4jqc39rpBM2dS4UDp9TEqu2MbLrffEDp2bTQt61Q"]
    networks:
      - tscs

    deploy:
      resources:
        limits:
          cpus: '12'
          memory: '18G'
        reservations:
          cpus: '6'
          memory: '12G'

    depends_on:
      - node1 


networks:
  tscs:
    driver: bridge
    
    
